name: Tag Build CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag release (contoh: v1.0.0). Kosongkan untuk auto."
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Decide tag
        run: |
          if [ -n "${{ github.event.inputs.tag }}" ]; then
            echo "TAG=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            echo "TAG=v${{ github.run_number }}" >> $GITHUB_ENV
          fi

      - name: Create & push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"

      - name: Build Frontend
        run: cd frontend && pnpm install --no-frozen-lockfile && pnpm build:release

      - name: Zip Frontend dist
        run: cd frontend/dist/ && zip -r frontend.zip * && mv frontend.zip ../

      - name: Build Telegram Frontend
        run: cd frontend && pnpm install --no-frozen-lockfile && pnpm build:telegram:release

      - name: Zip Telegram Frontend dist
        run: cd frontend/dist/ && zip -r telegram-frontend.zip * && mv telegram-frontend.zip ../

      - name: cp wrangler.toml
        run: cd worker && cp wrangler.toml.template wrangler.toml

      - name: Build Backend
        run: cd worker && pnpm install --no-frozen-lockfile && pnpm build

      - name: Move worker.js
        run: cd worker/dist && mv worker.js ../

      - name: Build Worker with wasm mail parser
        run: |
          cd worker
          pnpm add mail-parser-wasm-worker
          git apply ../.github/config/mail-parser-wasm-worker.patch
          pnpm build
          zip -r worker-with-wasm-mail-parser.zip dist/worker.js dist/*.wasm

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          files: |
            frontend/frontend.zip
            frontend/telegram-frontend.zip
            worker/worker.js
            worker/worker-with-wasm-mail-parser.zip
          overwrite_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
